image: docker:latest

services:
  - docker:dind

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository

stages:
 - build
 - package
 - publish
 
maven-build:
  image: qcm-git.mbrd.ru:5005/moos/dependence/maven-3-jdk-8:master
  stage: build
  tags:
    - tag1
  before_script:
    - sed -i 's/https\:\/\/nexus.boos.solutions\/repository\/farzoom-mvn/http\:\/\/qcm-nexus.mbrd.ru\/repository\/moos-maven-default/' ./pom.xml
  script:
    - mvn clean
    - mvn install -B
  after_script:
    - echo
  artifacts:
    paths:
    - target/*.jar

docker-build:
  stage: package
  tags:
    - tag4
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG ./
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    
docker-publish:
  stage: publish
  tags:
    - tag4
  script:
    - docker login -u s-bg-git -p __1Psf_on6qFvpmG5-CC http://qcm-nexus.mbrd.ru:8143
    - docker build -t "qcm-nexus.mbrd.ru:8143/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG" ./
    - docker push "qcm-nexus.mbrd.ru:8143/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG"