//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.11 at 07:49:54 AM MSK 
//


package com.farzoom.lime.adapter.cbs.service.integration.model.cre.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for CRE_CustInfo_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CRE_CustInfo_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}CustId" minOccurs="0"/>
 *         &lt;element name="PersonInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element ref="{}PersonName"/>
 *                   &lt;element ref="{}Gender"/>
 *                   &lt;element ref="{}Birthday"/>
 *                   &lt;element ref="{}BirthPlace"/>
 *                   &lt;element ref="{}Citizenship"/>
 *                   &lt;element ref="{}MaritalStatus"/>
 *                   &lt;element ref="{}EducationStatus"/>
 *                   &lt;element name="MilitaryStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="MilitaryDelay" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element ref="{}TaxId"/>
 *                   &lt;element ref="{}Dependents"/>
 *                   &lt;element ref="{}PersonNamePrev"/>
 *                   &lt;element name="IdentityCards" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{}IdentityCard" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element ref="{}ContactInfo"/>
 *                   &lt;element ref="{}EmploymentHistoryList" minOccurs="0"/>
 *                   &lt;element name="WeddingInfo" type="{}WeddingInfo_Type" minOccurs="0"/>
 *                   &lt;element ref="{}TotalExperiance" minOccurs="0"/>
 *                   &lt;element name="CustType" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Flags" type="{}Flags_Type"/>
 *         &lt;element name="IncomeList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="IncomeRec" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element ref="{}Type"/>
 *                             &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="CurAmt" type="{}CurrencyAmount"/>
 *                             &lt;element ref="{}BankInfo" minOccurs="0"/>
 *                             &lt;element name="ConfirmDoc" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{}Cust2CustList" minOccurs="0"/>
 *         &lt;element ref="{}WorkChng" minOccurs="0"/>
 *         &lt;element name="CalcInfo" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="VisCharCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CRE_CustInfo_Type", propOrder = {

})
public class CRECustInfoType {

    @XmlElement(name = "CustId")
    protected String custId;
    @XmlElement(name = "PersonInfo", required = true)
    protected CRECustInfoType.PersonInfo personInfo;
    @XmlElement(name = "Flags", required = true)
    protected FlagsType flags;
    @XmlElement(name = "IncomeList")
    protected CRECustInfoType.IncomeList incomeList;
    @XmlElement(name = "Cust2CustList")
    protected Cust2CustList cust2CustList;
    @XmlElement(name = "WorkChng")
    protected Integer workChng;
    @XmlElement(name = "CalcInfo")
    protected CRECustInfoType.CalcInfo calcInfo;

    /**
     * Gets the value of the custId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustId() {
        return custId;
    }

    /**
     * Sets the value of the custId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustId(String value) {
        this.custId = value;
    }

    /**
     * Gets the value of the personInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CRECustInfoType.PersonInfo }
     *     
     */
    public CRECustInfoType.PersonInfo getPersonInfo() {
        return personInfo;
    }

    /**
     * Sets the value of the personInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CRECustInfoType.PersonInfo }
     *     
     */
    public void setPersonInfo(CRECustInfoType.PersonInfo value) {
        this.personInfo = value;
    }

    /**
     * Gets the value of the flags property.
     * 
     * @return
     *     possible object is
     *     {@link FlagsType }
     *     
     */
    public FlagsType getFlags() {
        return flags;
    }

    /**
     * Sets the value of the flags property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagsType }
     *     
     */
    public void setFlags(FlagsType value) {
        this.flags = value;
    }

    /**
     * Gets the value of the incomeList property.
     * 
     * @return
     *     possible object is
     *     {@link CRECustInfoType.IncomeList }
     *     
     */
    public CRECustInfoType.IncomeList getIncomeList() {
        return incomeList;
    }

    /**
     * Sets the value of the incomeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link CRECustInfoType.IncomeList }
     *     
     */
    public void setIncomeList(CRECustInfoType.IncomeList value) {
        this.incomeList = value;
    }

    /**
     * Gets the value of the cust2CustList property.
     * 
     * @return
     *     possible object is
     *     {@link Cust2CustList }
     *     
     */
    public Cust2CustList getCust2CustList() {
        return cust2CustList;
    }

    /**
     * Sets the value of the cust2CustList property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cust2CustList }
     *     
     */
    public void setCust2CustList(Cust2CustList value) {
        this.cust2CustList = value;
    }

    /**
     * Gets the value of the workChng property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWorkChng() {
        return workChng;
    }

    /**
     * Sets the value of the workChng property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWorkChng(Integer value) {
        this.workChng = value;
    }

    /**
     * Gets the value of the calcInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CRECustInfoType.CalcInfo }
     *     
     */
    public CRECustInfoType.CalcInfo getCalcInfo() {
        return calcInfo;
    }

    /**
     * Sets the value of the calcInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CRECustInfoType.CalcInfo }
     *     
     */
    public void setCalcInfo(CRECustInfoType.CalcInfo value) {
        this.calcInfo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="VisCharCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class CalcInfo {

        @XmlElement(name = "VisCharCode")
        protected String visCharCode;

        /**
         * Gets the value of the visCharCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVisCharCode() {
            return visCharCode;
        }

        /**
         * Sets the value of the visCharCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVisCharCode(String value) {
            this.visCharCode = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="IncomeRec" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element ref="{}Type"/>
     *                   &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="CurAmt" type="{}CurrencyAmount"/>
     *                   &lt;element ref="{}BankInfo" minOccurs="0"/>
     *                   &lt;element name="ConfirmDoc" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "incomeRec"
    })
    public static class IncomeList {

        @XmlElement(name = "IncomeRec", required = true)
        protected List<CRECustInfoType.IncomeList.IncomeRec> incomeRec;

        /**
         * Gets the value of the incomeRec property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the incomeRec property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIncomeRec().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CRECustInfoType.IncomeList.IncomeRec }
         * 
         * 
         */
        public List<CRECustInfoType.IncomeList.IncomeRec> getIncomeRec() {
            if (incomeRec == null) {
                incomeRec = new ArrayList<CRECustInfoType.IncomeList.IncomeRec>();
            }
            return this.incomeRec;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element ref="{}Type"/>
         *         &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="CurAmt" type="{}CurrencyAmount"/>
         *         &lt;element ref="{}BankInfo" minOccurs="0"/>
         *         &lt;element name="ConfirmDoc" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class IncomeRec {

            @XmlElement(name = "Type", required = true)
            protected String type;
            @XmlElement(name = "Category", required = true)
            protected String category;
            @XmlElement(name = "CurAmt", required = true)
            protected CurrencyAmount curAmt;
            @XmlElement(name = "BankInfo")
            protected BankInfo bankInfo;
            @XmlElement(name = "ConfirmDoc")
            protected Boolean confirmDoc;

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

            /**
             * Gets the value of the category property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCategory() {
                return category;
            }

            /**
             * Sets the value of the category property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCategory(String value) {
                this.category = value;
            }

            /**
             * Gets the value of the curAmt property.
             * 
             * @return
             *     possible object is
             *     {@link CurrencyAmount }
             *     
             */
            public CurrencyAmount getCurAmt() {
                return curAmt;
            }

            /**
             * Sets the value of the curAmt property.
             * 
             * @param value
             *     allowed object is
             *     {@link CurrencyAmount }
             *     
             */
            public void setCurAmt(CurrencyAmount value) {
                this.curAmt = value;
            }

            /**
             * Gets the value of the bankInfo property.
             * 
             * @return
             *     possible object is
             *     {@link BankInfo }
             *     
             */
            public BankInfo getBankInfo() {
                return bankInfo;
            }

            /**
             * Sets the value of the bankInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link BankInfo }
             *     
             */
            public void setBankInfo(BankInfo value) {
                this.bankInfo = value;
            }

            /**
             * Gets the value of the confirmDoc property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isConfirmDoc() {
                return confirmDoc;
            }

            /**
             * Sets the value of the confirmDoc property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setConfirmDoc(Boolean value) {
                this.confirmDoc = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element ref="{}PersonName"/>
     *         &lt;element ref="{}Gender"/>
     *         &lt;element ref="{}Birthday"/>
     *         &lt;element ref="{}BirthPlace"/>
     *         &lt;element ref="{}Citizenship"/>
     *         &lt;element ref="{}MaritalStatus"/>
     *         &lt;element ref="{}EducationStatus"/>
     *         &lt;element name="MilitaryStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="MilitaryDelay" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element ref="{}TaxId"/>
     *         &lt;element ref="{}Dependents"/>
     *         &lt;element ref="{}PersonNamePrev"/>
     *         &lt;element name="IdentityCards" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{}IdentityCard" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element ref="{}ContactInfo"/>
     *         &lt;element ref="{}EmploymentHistoryList" minOccurs="0"/>
     *         &lt;element name="WeddingInfo" type="{}WeddingInfo_Type" minOccurs="0"/>
     *         &lt;element ref="{}TotalExperiance" minOccurs="0"/>
     *         &lt;element name="CustType" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class PersonInfo {

        @XmlElement(name = "PersonName", required = true)
        protected PersonNameType personName;
        @XmlElement(name = "Gender", required = true)
        protected String gender;
        @XmlElement(name = "Birthday", required = true)
        protected Date birthday;
        @XmlElement(name = "BirthPlace", required = true)
        protected String birthPlace;
        @XmlElement(name = "Citizenship", required = true)
        protected Citizenship citizenship;
        @XmlElement(name = "MaritalStatus", required = true)
        protected String maritalStatus;
        @XmlElement(name = "EducationStatus", required = true)
        protected String educationStatus;
        @XmlElement(name = "MilitaryStatus")
        protected String militaryStatus;
        @XmlElement(name = "MilitaryDelay")
        protected String militaryDelay;
        @XmlElement(name = "TaxId", required = true)
        protected String taxId;
        @XmlElement(name = "Dependents", required = true)
        protected String dependents;
        @XmlElement(name = "PersonNamePrev", required = true)
        protected PersonNamePrev personNamePrev;
        @XmlElement(name = "IdentityCards")
        protected CRECustInfoType.PersonInfo.IdentityCards identityCards;
        @XmlElement(name = "ContactInfo", required = true)
        protected ContactInfo contactInfo;
        @XmlElement(name = "EmploymentHistoryList")
        protected EmploymentHistoryList employmentHistoryList;
        @XmlElement(name = "WeddingInfo")
        protected WeddingInfoType weddingInfo;
        @XmlElement(name = "TotalExperiance")
        protected Integer totalExperiance;
        @XmlElement(name = "CustType")
        protected Object custType;

        /**
         * Gets the value of the personName property.
         * 
         * @return
         *     possible object is
         *     {@link PersonNameType }
         *     
         */
        public PersonNameType getPersonName() {
            return personName;
        }

        /**
         * Sets the value of the personName property.
         * 
         * @param value
         *     allowed object is
         *     {@link PersonNameType }
         *     
         */
        public void setPersonName(PersonNameType value) {
            this.personName = value;
        }

        /**
         * Gets the value of the gender property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGender() {
            return gender;
        }

        /**
         * Sets the value of the gender property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGender(String value) {
            this.gender = value;
        }

        /**
         * Gets the value of the birthday property.
         * 
         * @return
         *     possible object is
         *     {@link Date }
         *     
         */
        public Date getBirthday() {
            return birthday;
        }

        /**
         * Sets the value of the birthday property.
         * 
         * @param value
         *     allowed object is
         *     {@link Date }
         *     
         */
        public void setBirthday(Date value) {
            this.birthday = value;
        }

        /**
         * Gets the value of the birthPlace property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBirthPlace() {
            return birthPlace;
        }

        /**
         * Sets the value of the birthPlace property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBirthPlace(String value) {
            this.birthPlace = value;
        }

        /**
         * Gets the value of the citizenship property.
         * 
         * @return
         *     possible object is
         *     {@link Citizenship }
         *     
         */
        public Citizenship getCitizenship() {
            return citizenship;
        }

        /**
         * Sets the value of the citizenship property.
         * 
         * @param value
         *     allowed object is
         *     {@link Citizenship }
         *     
         */
        public void setCitizenship(Citizenship value) {
            this.citizenship = value;
        }

        /**
         * Gets the value of the maritalStatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMaritalStatus() {
            return maritalStatus;
        }

        /**
         * Sets the value of the maritalStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMaritalStatus(String value) {
            this.maritalStatus = value;
        }

        /**
         * Gets the value of the educationStatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEducationStatus() {
            return educationStatus;
        }

        /**
         * Sets the value of the educationStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEducationStatus(String value) {
            this.educationStatus = value;
        }

        /**
         * Gets the value of the militaryStatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMilitaryStatus() {
            return militaryStatus;
        }

        /**
         * Sets the value of the militaryStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMilitaryStatus(String value) {
            this.militaryStatus = value;
        }

        /**
         * Gets the value of the militaryDelay property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMilitaryDelay() {
            return militaryDelay;
        }

        /**
         * Sets the value of the militaryDelay property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMilitaryDelay(String value) {
            this.militaryDelay = value;
        }

        /**
         * Gets the value of the taxId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTaxId() {
            return taxId;
        }

        /**
         * Sets the value of the taxId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTaxId(String value) {
            this.taxId = value;
        }

        /**
         * Gets the value of the dependents property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDependents() {
            return dependents;
        }

        /**
         * Sets the value of the dependents property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDependents(String value) {
            this.dependents = value;
        }

        /**
         * Gets the value of the personNamePrev property.
         * 
         * @return
         *     possible object is
         *     {@link PersonNamePrev }
         *     
         */
        public PersonNamePrev getPersonNamePrev() {
            return personNamePrev;
        }

        /**
         * Sets the value of the personNamePrev property.
         * 
         * @param value
         *     allowed object is
         *     {@link PersonNamePrev }
         *     
         */
        public void setPersonNamePrev(PersonNamePrev value) {
            this.personNamePrev = value;
        }

        /**
         * Gets the value of the identityCards property.
         * 
         * @return
         *     possible object is
         *     {@link CRECustInfoType.PersonInfo.IdentityCards }
         *     
         */
        public CRECustInfoType.PersonInfo.IdentityCards getIdentityCards() {
            return identityCards;
        }

        /**
         * Sets the value of the identityCards property.
         * 
         * @param value
         *     allowed object is
         *     {@link CRECustInfoType.PersonInfo.IdentityCards }
         *     
         */
        public void setIdentityCards(CRECustInfoType.PersonInfo.IdentityCards value) {
            this.identityCards = value;
        }

        /**
         * Gets the value of the contactInfo property.
         * 
         * @return
         *     possible object is
         *     {@link ContactInfo }
         *     
         */
        public ContactInfo getContactInfo() {
            return contactInfo;
        }

        /**
         * Sets the value of the contactInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link ContactInfo }
         *     
         */
        public void setContactInfo(ContactInfo value) {
            this.contactInfo = value;
        }

        /**
         * Gets the value of the employmentHistoryList property.
         * 
         * @return
         *     possible object is
         *     {@link EmploymentHistoryList }
         *     
         */
        public EmploymentHistoryList getEmploymentHistoryList() {
            return employmentHistoryList;
        }

        /**
         * Sets the value of the employmentHistoryList property.
         * 
         * @param value
         *     allowed object is
         *     {@link EmploymentHistoryList }
         *     
         */
        public void setEmploymentHistoryList(EmploymentHistoryList value) {
            this.employmentHistoryList = value;
        }

        /**
         * Gets the value of the weddingInfo property.
         * 
         * @return
         *     possible object is
         *     {@link WeddingInfoType }
         *     
         */
        public WeddingInfoType getWeddingInfo() {
            return weddingInfo;
        }

        /**
         * Sets the value of the weddingInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link WeddingInfoType }
         *     
         */
        public void setWeddingInfo(WeddingInfoType value) {
            this.weddingInfo = value;
        }

        /**
         * Gets the value of the totalExperiance property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getTotalExperiance() {
            return totalExperiance;
        }

        /**
         * Sets the value of the totalExperiance property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setTotalExperiance(Integer value) {
            this.totalExperiance = value;
        }

        /**
         * Gets the value of the custType property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getCustType() {
            return custType;
        }

        /**
         * Sets the value of the custType property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setCustType(Object value) {
            this.custType = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{}IdentityCard" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "identityCard"
        })
        public static class IdentityCards {

            @XmlElement(name = "IdentityCard")
            protected IdentityCard identityCard;

            /**
             * Gets the value of the identityCard property.
             * 
             * @return
             *     possible object is
             *     {@link IdentityCard }
             *     
             */
            public IdentityCard getIdentityCard() {
                return identityCard;
            }

            /**
             * Sets the value of the identityCard property.
             * 
             * @param value
             *     allowed object is
             *     {@link IdentityCard }
             *     
             */
            public void setIdentityCard(IdentityCard value) {
                this.identityCard = value;
            }

        }

    }

}
