//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.11 at 07:49:54 AM MSK 
//


package com.farzoom.lime.adapter.cbs.service.integration.model.cre.request;

import com.farzoom.lime.adapter.cbs.service.integration.dataadapters.BooleanAdapter;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Флаги
 * 
 * <p>Java class for Flags_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Flags_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Student" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Work" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Pensioner" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Criminalliability" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="CriminalSuspect" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="LowRespondent" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="UnSatjudgement" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="UnSettledDebt" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="OpenRequest" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="CreditDeal" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="PlanChanges" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="LoanFee" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="DebtDelay" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="AddWork" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Deposit" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ControlAnotherPerson" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="PassBKI" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="PassBKIDt" type="{}Date" minOccurs="0"/>
 *         &lt;element name="LoanHistory" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Signature" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="NoInsAcctId" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="EmplSpouse" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="PassPFR" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Gosuslugi" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="PhotoStatusCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Flags_Type", propOrder = {

})
public class FlagsType {

    @XmlElement(name = "Student")
    protected Boolean student;
    @XmlElement(name = "Work")
    protected Boolean work;
    @XmlElement(name = "Pensioner")
    protected Boolean pensioner;
    @XmlElement(name = "Criminalliability")
    protected Boolean criminalliability;
    @XmlElement(name = "CriminalSuspect")
    protected Boolean criminalSuspect;
    @XmlElement(name = "LowRespondent")
    protected Boolean lowRespondent;
    @XmlElement(name = "UnSatjudgement")
    protected Boolean unSatjudgement;
    @XmlElement(name = "UnSettledDebt")
    protected Boolean unSettledDebt;
    @XmlElement(name = "OpenRequest")
    protected Boolean openRequest;
    @XmlElement(name = "CreditDeal")
    protected Boolean creditDeal;
    @XmlElement(name = "PlanChanges")
    protected Boolean planChanges;
    @XmlElement(name = "LoanFee")
    protected Boolean loanFee;
    @XmlElement(name = "DebtDelay")
    protected Boolean debtDelay;
    @XmlElement(name = "AddWork")
    protected Boolean addWork;
    @XmlElement(name = "Deposit")
    protected Boolean deposit;
    @XmlElement(name = "ControlAnotherPerson")
    protected Boolean controlAnotherPerson;
    @XmlElement(name = "PassBKI")
    @XmlJavaTypeAdapter(BooleanAdapter.class)
    protected Boolean passBKI;
    @XmlElement(name = "PassBKIDt")
    protected Date passBKIDt;
    @XmlElement(name = "LoanHistory")
    protected Boolean loanHistory;
    @XmlElement(name = "Signature")
    protected Boolean signature;
    @XmlElement(name = "NoInsAcctId")
    protected Boolean noInsAcctId;
    @XmlElement(name = "EmplSpouse")
    protected Boolean emplSpouse;
    @XmlElement(name = "PassPFR")
    protected Boolean passPFR;
    @XmlElement(name = "Gosuslugi")
    protected Boolean gosuslugi;
    @XmlElement(name = "PhotoStatusCode")
    protected String photoStatusCode;

    /**
     * Gets the value of the student property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isStudent() {
        return student;
    }

    /**
     * Sets the value of the student property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStudent(Boolean value) {
        this.student = value;
    }

    /**
     * Gets the value of the work property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isWork() {
        return work;
    }

    /**
     * Sets the value of the work property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWork(Boolean value) {
        this.work = value;
    }

    /**
     * Gets the value of the pensioner property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPensioner() {
        return pensioner;
    }

    /**
     * Sets the value of the pensioner property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPensioner(Boolean value) {
        this.pensioner = value;
    }

    /**
     * Gets the value of the criminalliability property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCriminalliability() {
        return criminalliability;
    }

    /**
     * Sets the value of the criminalliability property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCriminalliability(Boolean value) {
        this.criminalliability = value;
    }

    /**
     * Gets the value of the criminalSuspect property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCriminalSuspect() {
        return criminalSuspect;
    }

    /**
     * Sets the value of the criminalSuspect property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCriminalSuspect(Boolean value) {
        this.criminalSuspect = value;
    }

    /**
     * Gets the value of the lowRespondent property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLowRespondent() {
        return lowRespondent;
    }

    /**
     * Sets the value of the lowRespondent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLowRespondent(Boolean value) {
        this.lowRespondent = value;
    }

    /**
     * Gets the value of the unSatjudgement property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUnSatjudgement() {
        return unSatjudgement;
    }

    /**
     * Sets the value of the unSatjudgement property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUnSatjudgement(Boolean value) {
        this.unSatjudgement = value;
    }

    /**
     * Gets the value of the unSettledDebt property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUnSettledDebt() {
        return unSettledDebt;
    }

    /**
     * Sets the value of the unSettledDebt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUnSettledDebt(Boolean value) {
        this.unSettledDebt = value;
    }

    /**
     * Gets the value of the openRequest property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOpenRequest() {
        return openRequest;
    }

    /**
     * Sets the value of the openRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOpenRequest(Boolean value) {
        this.openRequest = value;
    }

    /**
     * Gets the value of the creditDeal property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCreditDeal() {
        return creditDeal;
    }

    /**
     * Sets the value of the creditDeal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCreditDeal(Boolean value) {
        this.creditDeal = value;
    }

    /**
     * Gets the value of the planChanges property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPlanChanges() {
        return planChanges;
    }

    /**
     * Sets the value of the planChanges property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPlanChanges(Boolean value) {
        this.planChanges = value;
    }

    /**
     * Gets the value of the loanFee property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLoanFee() {
        return loanFee;
    }

    /**
     * Sets the value of the loanFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLoanFee(Boolean value) {
        this.loanFee = value;
    }

    /**
     * Gets the value of the debtDelay property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDebtDelay() {
        return debtDelay;
    }

    /**
     * Sets the value of the debtDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDebtDelay(Boolean value) {
        this.debtDelay = value;
    }

    /**
     * Gets the value of the addWork property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAddWork() {
        return addWork;
    }

    /**
     * Sets the value of the addWork property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAddWork(Boolean value) {
        this.addWork = value;
    }

    /**
     * Gets the value of the deposit property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDeposit() {
        return deposit;
    }

    /**
     * Sets the value of the deposit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDeposit(Boolean value) {
        this.deposit = value;
    }

    /**
     * Gets the value of the controlAnotherPerson property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isControlAnotherPerson() {
        return controlAnotherPerson;
    }

    /**
     * Sets the value of the controlAnotherPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setControlAnotherPerson(Boolean value) {
        this.controlAnotherPerson = value;
    }

    /**
     * Gets the value of the passBKI property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPassBKI() {
        return passBKI;
    }

    /**
     * Sets the value of the passBKI property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPassBKI(Boolean value) {
        this.passBKI = value;
    }

    /**
     * Gets the value of the passBKIDt property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getPassBKIDt() {
        return passBKIDt;
    }

    /**
     * Sets the value of the passBKIDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setPassBKIDt(Date value) {
        this.passBKIDt = value;
    }

    /**
     * Gets the value of the loanHistory property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLoanHistory() {
        return loanHistory;
    }

    /**
     * Sets the value of the loanHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLoanHistory(Boolean value) {
        this.loanHistory = value;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSignature(Boolean value) {
        this.signature = value;
    }

    /**
     * Gets the value of the noInsAcctId property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNoInsAcctId() {
        return noInsAcctId;
    }

    /**
     * Sets the value of the noInsAcctId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNoInsAcctId(Boolean value) {
        this.noInsAcctId = value;
    }

    /**
     * Gets the value of the emplSpouse property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEmplSpouse() {
        return emplSpouse;
    }

    /**
     * Sets the value of the emplSpouse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEmplSpouse(Boolean value) {
        this.emplSpouse = value;
    }

    /**
     * Gets the value of the passPFR property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPassPFR() {
        return passPFR;
    }

    /**
     * Sets the value of the passPFR property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPassPFR(Boolean value) {
        this.passPFR = value;
    }

    /**
     * Gets the value of the gosuslugi property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGosuslugi() {
        return gosuslugi;
    }

    /**
     * Sets the value of the gosuslugi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGosuslugi(Boolean value) {
        this.gosuslugi = value;
    }

    /**
     * Gets the value of the photoStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhotoStatusCode() {
        return photoStatusCode;
    }

    /**
     * Sets the value of the photoStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhotoStatusCode(String value) {
        this.photoStatusCode = value;
    }

}
