//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.06 at 07:01:04 PM EET 
//


package com.farzoom.lime.adapter.cbs.service.integration.model.smsinfomod.request;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}ServerInfo"/>
 *         &lt;element name="BankSvcRq">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="OrgInfo" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element ref="{}OrgId"/>
 *                             &lt;element ref="{}TaxId"/>
 *                             &lt;element ref="{}Name"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element ref="{}Action" minOccurs="0"/>
 *                   &lt;element name="StartDt" type="{}Date" minOccurs="0"/>
 *                   &lt;element name="BankAcctList">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="BankAcctRec" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;all>
 *                                       &lt;element ref="{}AcctId"/>
 *                                       &lt;element name="AcctFee" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                                       &lt;element ref="{}Id"/>
 *                                       &lt;element ref="{}BankInfo"/>
 *                                       &lt;element name="SvcList" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="SvcRec" maxOccurs="unbounded">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;all>
 *                                                           &lt;element ref="{}Action" minOccurs="0"/>
 *                                                           &lt;element ref="{}PhoneNum"/>
 *                                                           &lt;element ref="{}SvcName" minOccurs="0"/>
 *                                                           &lt;element name="SvcCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                                         &lt;/all>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/all>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "FDX")
public class SmsBankInfoModRequest {

    @XmlElement(name = "ServerInfo", required = true)
    protected ServerInfoType serverInfo;
    @XmlElement(name = "BankSvcRq", required = true)
    protected SmsBankInfoModRequest.BankSvcRq bankSvcRq;

    /**
     * Gets the value of the serverInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ServerInfoType }
     *     
     */
    public ServerInfoType getServerInfo() {
        return serverInfo;
    }

    /**
     * Sets the value of the serverInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServerInfoType }
     *     
     */
    public void setServerInfo(ServerInfoType value) {
        this.serverInfo = value;
    }

    /**
     * Gets the value of the bankSvcRq property.
     * 
     * @return
     *     possible object is
     *     {@link SmsBankInfoModRequest.BankSvcRq }
     *     
     */
    public SmsBankInfoModRequest.BankSvcRq getBankSvcRq() {
        return bankSvcRq;
    }

    /**
     * Sets the value of the bankSvcRq property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmsBankInfoModRequest.BankSvcRq }
     *     
     */
    public void setBankSvcRq(SmsBankInfoModRequest.BankSvcRq value) {
        this.bankSvcRq = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="OrgInfo" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element ref="{}OrgId"/>
     *                   &lt;element ref="{}TaxId"/>
     *                   &lt;element ref="{}Name"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element ref="{}Action" minOccurs="0"/>
     *         &lt;element name="StartDt" type="{}Date" minOccurs="0"/>
     *         &lt;element name="BankAcctList">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="BankAcctRec" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;all>
     *                             &lt;element ref="{}AcctId"/>
     *                             &lt;element name="AcctFee" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                             &lt;element ref="{}Id"/>
     *                             &lt;element ref="{}BankInfo"/>
     *                             &lt;element name="SvcList" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="SvcRec" maxOccurs="unbounded">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;all>
     *                                                 &lt;element ref="{}Action" minOccurs="0"/>
     *                                                 &lt;element ref="{}PhoneNum"/>
     *                                                 &lt;element ref="{}SvcName" minOccurs="0"/>
     *                                                 &lt;element name="SvcCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                                               &lt;/all>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/all>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class BankSvcRq {

        @XmlElement(name = "OrgInfo")
        protected SmsBankInfoModRequest.BankSvcRq.OrgInfo orgInfo;
        @XmlElement(name = "Action")
        protected String action;
        @XmlElement(name = "StartDt")
        protected Date startDt;
        @XmlElement(name = "BankAcctList", required = true)
        protected SmsBankInfoModRequest.BankSvcRq.BankAcctList bankAcctList;

        /**
         * Gets the value of the orgInfo property.
         * 
         * @return
         *     possible object is
         *     {@link SmsBankInfoModRequest.BankSvcRq.OrgInfo }
         *     
         */
        public SmsBankInfoModRequest.BankSvcRq.OrgInfo getOrgInfo() {
            return orgInfo;
        }

        /**
         * Sets the value of the orgInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link SmsBankInfoModRequest.BankSvcRq.OrgInfo }
         *     
         */
        public void setOrgInfo(SmsBankInfoModRequest.BankSvcRq.OrgInfo value) {
            this.orgInfo = value;
        }

        /**
         * Gets the value of the action property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAction() {
            return action;
        }

        /**
         * Sets the value of the action property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAction(String value) {
            this.action = value;
        }

        /**
         * Gets the value of the startDt property.
         * 
         * @return
         *     possible object is
         *     {@link Date }
         *     
         */
        public Date getStartDt() {
            return startDt;
        }

        /**
         * Sets the value of the startDt property.
         * 
         * @param value
         *     allowed object is
         *     {@link Date }
         *     
         */
        public void setStartDt(Date value) {
            this.startDt = value;
        }

        /**
         * Gets the value of the bankAcctList property.
         * 
         * @return
         *     possible object is
         *     {@link SmsBankInfoModRequest.BankSvcRq.BankAcctList }
         *     
         */
        public SmsBankInfoModRequest.BankSvcRq.BankAcctList getBankAcctList() {
            return bankAcctList;
        }

        /**
         * Sets the value of the bankAcctList property.
         * 
         * @param value
         *     allowed object is
         *     {@link SmsBankInfoModRequest.BankSvcRq.BankAcctList }
         *     
         */
        public void setBankAcctList(SmsBankInfoModRequest.BankSvcRq.BankAcctList value) {
            this.bankAcctList = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="BankAcctRec" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;all>
         *                   &lt;element ref="{}AcctId"/>
         *                   &lt;element name="AcctFee" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *                   &lt;element ref="{}Id"/>
         *                   &lt;element ref="{}BankInfo"/>
         *                   &lt;element name="SvcList" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="SvcRec" maxOccurs="unbounded">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;all>
         *                                       &lt;element ref="{}Action" minOccurs="0"/>
         *                                       &lt;element ref="{}PhoneNum"/>
         *                                       &lt;element ref="{}SvcName" minOccurs="0"/>
         *                                       &lt;element name="SvcCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                                     &lt;/all>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/all>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "bankAcctRec"
        })
        public static class BankAcctList {

            @XmlElement(name = "BankAcctRec", required = true)
            protected List<SmsBankInfoModRequest.BankSvcRq.BankAcctList.BankAcctRec> bankAcctRec;

            /**
             * Gets the value of the bankAcctRec property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the bankAcctRec property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getBankAcctRec().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link SmsBankInfoModRequest.BankSvcRq.BankAcctList.BankAcctRec }
             * 
             * 
             */
            public List<SmsBankInfoModRequest.BankSvcRq.BankAcctList.BankAcctRec> getBankAcctRec() {
                if (bankAcctRec == null) {
                    bankAcctRec = new ArrayList<SmsBankInfoModRequest.BankSvcRq.BankAcctList.BankAcctRec>();
                }
                return this.bankAcctRec;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;all>
             *         &lt;element ref="{}AcctId"/>
             *         &lt;element name="AcctFee" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
             *         &lt;element ref="{}Id"/>
             *         &lt;element ref="{}BankInfo"/>
             *         &lt;element name="SvcList" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="SvcRec" maxOccurs="unbounded">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;all>
             *                             &lt;element ref="{}Action" minOccurs="0"/>
             *                             &lt;element ref="{}PhoneNum"/>
             *                             &lt;element ref="{}SvcName" minOccurs="0"/>
             *                             &lt;element name="SvcCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *                           &lt;/all>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/all>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {

            })
            public static class BankAcctRec {

                @XmlElement(name = "AcctId", required = true)
                protected String acctId;
                @XmlElement(name = "AcctFee")
                protected Integer acctFee; //XXX по XSD boolean, изменено вручную
                @XmlElement(name = "Id", required = true)
                protected String id;
                @XmlElement(name = "BankInfo", required = true)
                protected BankInfo bankInfo;
                @XmlElement(name = "SvcList")
                protected SmsBankInfoModRequest.BankSvcRq.BankAcctList.BankAcctRec.SvcList svcList;

                /**
                 * Gets the value of the acctId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAcctId() {
                    return acctId;
                }

                /**
                 * Sets the value of the acctId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAcctId(String value) {
                    this.acctId = value;
                }

                /**
                 * Gets the value of the acctFee property.
                 * 
                 */
                public Integer getAcctFee() {
                    return acctFee;
                }

                /**
                 * Sets the value of the acctFee property.
                 * 
                 */
                public void setAcctFee(Integer value) {
                    this.acctFee = value;
                }

                /**
                 * Gets the value of the id property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setId(String value) {
                    this.id = value;
                }

                /**
                 * Gets the value of the bankInfo property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BankInfo }
                 *     
                 */
                public BankInfo getBankInfo() {
                    return bankInfo;
                }

                /**
                 * Sets the value of the bankInfo property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BankInfo }
                 *     
                 */
                public void setBankInfo(BankInfo value) {
                    this.bankInfo = value;
                }

                /**
                 * Gets the value of the svcList property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link SmsBankInfoModRequest.BankSvcRq.BankAcctList.BankAcctRec.SvcList }
                 *     
                 */
                public SmsBankInfoModRequest.BankSvcRq.BankAcctList.BankAcctRec.SvcList getSvcList() {
                    return svcList;
                }

                /**
                 * Sets the value of the svcList property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link SmsBankInfoModRequest.BankSvcRq.BankAcctList.BankAcctRec.SvcList }
                 *     
                 */
                public void setSvcList(SmsBankInfoModRequest.BankSvcRq.BankAcctList.BankAcctRec.SvcList value) {
                    this.svcList = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="SvcRec" maxOccurs="unbounded">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;all>
                 *                   &lt;element ref="{}Action" minOccurs="0"/>
                 *                   &lt;element ref="{}PhoneNum"/>
                 *                   &lt;element ref="{}SvcName" minOccurs="0"/>
                 *                   &lt;element name="SvcCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
                 *                 &lt;/all>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "svcRec"
                })
                public static class SvcList {

                    @XmlElement(name = "SvcRec", required = true)
                    protected List<SmsBankInfoModRequest.BankSvcRq.BankAcctList.BankAcctRec.SvcList.SvcRec> svcRec;

                    /**
                     * Gets the value of the svcRec property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the svcRec property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getSvcRec().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link SmsBankInfoModRequest.BankSvcRq.BankAcctList.BankAcctRec.SvcList.SvcRec }
                     * 
                     * 
                     */
                    public List<SmsBankInfoModRequest.BankSvcRq.BankAcctList.BankAcctRec.SvcList.SvcRec> getSvcRec() {
                        if (svcRec == null) {
                            svcRec = new ArrayList<SmsBankInfoModRequest.BankSvcRq.BankAcctList.BankAcctRec.SvcList.SvcRec>();
                        }
                        return this.svcRec;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;all>
                     *         &lt;element ref="{}Action" minOccurs="0"/>
                     *         &lt;element ref="{}PhoneNum"/>
                     *         &lt;element ref="{}SvcName" minOccurs="0"/>
                     *         &lt;element name="SvcCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
                     *       &lt;/all>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {

                    })
                    public static class SvcRec {

                        @XmlElement(name = "Action")
                        protected String action;
                        @XmlElement(name = "PhoneNum", required = true)
                        protected PhoneNum phoneNum;
                        @XmlElement(name = "SvcName")
                        protected String svcName;
                        @XmlElement(name = "SvcCode")
                        protected String svcCode;

                        /**
                         * Gets the value of the action property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getAction() {
                            return action;
                        }

                        /**
                         * Sets the value of the action property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setAction(String value) {
                            this.action = value;
                        }

                        /**
                         * Gets the value of the phoneNum property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link PhoneNum }
                         *     
                         */
                        public PhoneNum getPhoneNum() {
                            return phoneNum;
                        }

                        /**
                         * Sets the value of the phoneNum property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link PhoneNum }
                         *     
                         */
                        public void setPhoneNum(PhoneNum value) {
                            this.phoneNum = value;
                        }

                        /**
                         * Gets the value of the svcName property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getSvcName() {
                            return svcName;
                        }

                        /**
                         * Sets the value of the svcName property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setSvcName(String value) {
                            this.svcName = value;
                        }

                        /**
                         * Gets the value of the svcCode property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getSvcCode() {
                            return svcCode;
                        }

                        /**
                         * Sets the value of the svcCode property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setSvcCode(String value) {
                            this.svcCode = value;
                        }

                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element ref="{}OrgId"/>
         *         &lt;element ref="{}TaxId"/>
         *         &lt;element ref="{}Name"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class OrgInfo {

            @XmlElement(name = "OrgId", required = true)
            protected String orgId;
            @XmlElement(name = "TaxId", required = true)
            protected String taxId;
            @XmlElement(name = "Name", required = true)
            protected String name;

            /**
             * Gets the value of the orgId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOrgId() {
                return orgId;
            }

            /**
             * Sets the value of the orgId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOrgId(String value) {
                this.orgId = value;
            }

            /**
             * Gets the value of the taxId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTaxId() {
                return taxId;
            }

            /**
             * Sets the value of the taxId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTaxId(String value) {
                this.taxId = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

        }

    }

}
