//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.19 at 11:25:25 AM MSK 
//


package com.farzoom.lime.adapter.cbs.service.integration.model.afs.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for AfsCustInfo_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AfsCustInfo_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}Id" minOccurs="0"/>
 *         &lt;element ref="{}FraudCode" minOccurs="0"/>
 *         &lt;element ref="{}CustId" minOccurs="0"/>
 *         &lt;element name="PersonInfo" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element ref="{}PersonName" minOccurs="0"/>
 *                   &lt;element ref="{}PersonNamePrev" minOccurs="0"/>
 *                   &lt;element ref="{}Birthday" minOccurs="0"/>
 *                   &lt;element ref="{}BirthPlace" minOccurs="0"/>
 *                   &lt;element ref="{}Gender" minOccurs="0"/>
 *                   &lt;element ref="{}Citizenship" minOccurs="0"/>
 *                   &lt;element ref="{}Resident" minOccurs="0"/>
 *                   &lt;element name="Dependents" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element ref="{}MaritalStatus" minOccurs="0"/>
 *                   &lt;element name="MilitaryStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="TotalExperiance" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="WeddingInfo" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="RegDt" type="{}Date" minOccurs="0"/>
 *                             &lt;element name="MarriageContract" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="DivisionProperty" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Childs" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="MilitaryDelay" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="AddCitizenship" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element ref="{}Country"/>
 *                             &lt;element ref="{}CountryName" minOccurs="0"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="EducationStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="ConsularRegistry" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TotalIncome" type="{}CurrencyAmount" minOccurs="0"/>
 *         &lt;element name="TotalOutlay" type="{}CurrencyAmount" minOccurs="0"/>
 *         &lt;element name="IncomeList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="IncomeRec" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element ref="{}Type"/>
 *                             &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="CurAmt" type="{}CurrencyAmount"/>
 *                             &lt;element ref="{}BankInfo" minOccurs="0"/>
 *                             &lt;element name="ConfirmDoc" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="IPDLStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="WorkChng" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="TransportCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Flags" type="{}Flags_Type" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AfsCustInfo_Type", propOrder = {

})
public class AfsCustInfoType {

    @XmlElement(name = "Id")
    protected Integer id;
    @XmlElement(name = "FraudCode")
    protected String fraudCode;
    @XmlElement(name = "CustId")
    protected String custId;
    @XmlElement(name = "PersonInfo")
    protected AfsCustInfoType.PersonInfo personInfo;
    @XmlElement(name = "TotalIncome")
    protected CurrencyAmount totalIncome;
    @XmlElement(name = "TotalOutlay")
    protected CurrencyAmount totalOutlay;
    @XmlElement(name = "IncomeList")
    protected AfsCustInfoType.IncomeList incomeList;
    @XmlElement(name = "IPDLStatus")
    protected String ipdlStatus;
    @XmlElement(name = "WorkChng")
    protected Integer workChng;
    @XmlElement(name = "TransportCount")
    protected Integer transportCount;
    @XmlElement(name = "Flags")
    protected FlagsType flags;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the fraudCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFraudCode() {
        return fraudCode;
    }

    /**
     * Sets the value of the fraudCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFraudCode(String value) {
        this.fraudCode = value;
    }

    /**
     * Gets the value of the custId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustId() {
        return custId;
    }

    /**
     * Sets the value of the custId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustId(String value) {
        this.custId = value;
    }

    /**
     * Gets the value of the personInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AfsCustInfoType.PersonInfo }
     *     
     */
    public AfsCustInfoType.PersonInfo getPersonInfo() {
        return personInfo;
    }

    /**
     * Sets the value of the personInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AfsCustInfoType.PersonInfo }
     *     
     */
    public void setPersonInfo(AfsCustInfoType.PersonInfo value) {
        this.personInfo = value;
    }

    /**
     * Gets the value of the totalIncome property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyAmount }
     *     
     */
    public CurrencyAmount getTotalIncome() {
        return totalIncome;
    }

    /**
     * Sets the value of the totalIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyAmount }
     *     
     */
    public void setTotalIncome(CurrencyAmount value) {
        this.totalIncome = value;
    }

    /**
     * Gets the value of the totalOutlay property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyAmount }
     *     
     */
    public CurrencyAmount getTotalOutlay() {
        return totalOutlay;
    }

    /**
     * Sets the value of the totalOutlay property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyAmount }
     *     
     */
    public void setTotalOutlay(CurrencyAmount value) {
        this.totalOutlay = value;
    }

    /**
     * Gets the value of the incomeList property.
     * 
     * @return
     *     possible object is
     *     {@link AfsCustInfoType.IncomeList }
     *     
     */
    public AfsCustInfoType.IncomeList getIncomeList() {
        return incomeList;
    }

    /**
     * Sets the value of the incomeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AfsCustInfoType.IncomeList }
     *     
     */
    public void setIncomeList(AfsCustInfoType.IncomeList value) {
        this.incomeList = value;
    }

    /**
     * Gets the value of the ipdlStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIPDLStatus() {
        return ipdlStatus;
    }

    /**
     * Sets the value of the ipdlStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIPDLStatus(String value) {
        this.ipdlStatus = value;
    }

    /**
     * Gets the value of the workChng property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWorkChng() {
        return workChng;
    }

    /**
     * Sets the value of the workChng property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWorkChng(Integer value) {
        this.workChng = value;
    }

    /**
     * Gets the value of the transportCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTransportCount() {
        return transportCount;
    }

    /**
     * Sets the value of the transportCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTransportCount(Integer value) {
        this.transportCount = value;
    }

    /**
     * Gets the value of the flags property.
     * 
     * @return
     *     possible object is
     *     {@link FlagsType }
     *     
     */
    public FlagsType getFlags() {
        return flags;
    }

    /**
     * Sets the value of the flags property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagsType }
     *     
     */
    public void setFlags(FlagsType value) {
        this.flags = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="IncomeRec" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element ref="{}Type"/>
     *                   &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="CurAmt" type="{}CurrencyAmount"/>
     *                   &lt;element ref="{}BankInfo" minOccurs="0"/>
     *                   &lt;element name="ConfirmDoc" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "incomeRec"
    })
    public static class IncomeList {

        @XmlElement(name = "IncomeRec", required = true)
        protected List<AfsCustInfoType.IncomeList.IncomeRec> incomeRec;

        /**
         * Gets the value of the incomeRec property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the incomeRec property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIncomeRec().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AfsCustInfoType.IncomeList.IncomeRec }
         * 
         * 
         */
        public List<AfsCustInfoType.IncomeList.IncomeRec> getIncomeRec() {
            if (incomeRec == null) {
                incomeRec = new ArrayList<AfsCustInfoType.IncomeList.IncomeRec>();
            }
            return this.incomeRec;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element ref="{}Type"/>
         *         &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="CurAmt" type="{}CurrencyAmount"/>
         *         &lt;element ref="{}BankInfo" minOccurs="0"/>
         *         &lt;element name="ConfirmDoc" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class IncomeRec {

            @XmlElement(name = "Type", required = true)
            protected String type;
            @XmlElement(name = "Category", required = true)
            protected String category;
            @XmlElement(name = "CurAmt", required = true)
            protected CurrencyAmount curAmt;
            @XmlElement(name = "BankInfo")
            protected BankInfo bankInfo;
            @XmlElement(name = "ConfirmDoc")
            protected Boolean confirmDoc;

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

            /**
             * Gets the value of the category property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCategory() {
                return category;
            }

            /**
             * Sets the value of the category property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCategory(String value) {
                this.category = value;
            }

            /**
             * Gets the value of the curAmt property.
             * 
             * @return
             *     possible object is
             *     {@link CurrencyAmount }
             *     
             */
            public CurrencyAmount getCurAmt() {
                return curAmt;
            }

            /**
             * Sets the value of the curAmt property.
             * 
             * @param value
             *     allowed object is
             *     {@link CurrencyAmount }
             *     
             */
            public void setCurAmt(CurrencyAmount value) {
                this.curAmt = value;
            }

            /**
             * Gets the value of the bankInfo property.
             * 
             * @return
             *     possible object is
             *     {@link BankInfo }
             *     
             */
            public BankInfo getBankInfo() {
                return bankInfo;
            }

            /**
             * Sets the value of the bankInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link BankInfo }
             *     
             */
            public void setBankInfo(BankInfo value) {
                this.bankInfo = value;
            }

            /**
             * Gets the value of the confirmDoc property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isConfirmDoc() {
                return confirmDoc;
            }

            /**
             * Sets the value of the confirmDoc property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setConfirmDoc(Boolean value) {
                this.confirmDoc = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element ref="{}PersonName" minOccurs="0"/>
     *         &lt;element ref="{}PersonNamePrev" minOccurs="0"/>
     *         &lt;element ref="{}Birthday" minOccurs="0"/>
     *         &lt;element ref="{}BirthPlace" minOccurs="0"/>
     *         &lt;element ref="{}Gender" minOccurs="0"/>
     *         &lt;element ref="{}Citizenship" minOccurs="0"/>
     *         &lt;element ref="{}Resident" minOccurs="0"/>
     *         &lt;element name="Dependents" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element ref="{}MaritalStatus" minOccurs="0"/>
     *         &lt;element name="MilitaryStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="TotalExperiance" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="WeddingInfo" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="RegDt" type="{}Date" minOccurs="0"/>
     *                   &lt;element name="MarriageContract" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                   &lt;element name="DivisionProperty" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Childs" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="MilitaryDelay" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="AddCitizenship" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element ref="{}Country"/>
     *                   &lt;element ref="{}CountryName" minOccurs="0"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="EducationStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="ConsularRegistry" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class PersonInfo {

        @XmlElement(name = "PersonName")
        protected PersonNameType personName;
        @XmlElement(name = "PersonNamePrev")
        protected PersonNamePrev personNamePrev;
        @XmlElement(name = "Birthday")
        protected Date birthday;
        @XmlElement(name = "BirthPlace")
        protected String birthPlace;
        @XmlElement(name = "Gender")
        protected String gender;
        @XmlElement(name = "Citizenship")
        protected Citizenship citizenship;
        @XmlElement(name = "Resident", defaultValue = "true")
        protected Boolean resident;
        @XmlElement(name = "Dependents")
        protected String dependents;
        @XmlElement(name = "MaritalStatus")
        protected String maritalStatus;
        @XmlElement(name = "MilitaryStatus")
        protected String militaryStatus;
        @XmlElement(name = "TotalExperiance")
        protected Integer totalExperiance;
        @XmlElement(name = "WeddingInfo")
        protected AfsCustInfoType.PersonInfo.WeddingInfo weddingInfo;
        @XmlElement(name = "MilitaryDelay")
        protected String militaryDelay;
        @XmlElement(name = "AddCitizenship")
        protected AfsCustInfoType.PersonInfo.AddCitizenship addCitizenship;
        @XmlElement(name = "EducationStatus")
        protected String educationStatus;
        @XmlElement(name = "ConsularRegistry")
        protected String consularRegistry;

        /**
         * Gets the value of the personName property.
         * 
         * @return
         *     possible object is
         *     {@link PersonNameType }
         *     
         */
        public PersonNameType getPersonName() {
            return personName;
        }

        /**
         * Sets the value of the personName property.
         * 
         * @param value
         *     allowed object is
         *     {@link PersonNameType }
         *     
         */
        public void setPersonName(PersonNameType value) {
            this.personName = value;
        }

        /**
         * Gets the value of the personNamePrev property.
         * 
         * @return
         *     possible object is
         *     {@link PersonNamePrev }
         *     
         */
        public PersonNamePrev getPersonNamePrev() {
            return personNamePrev;
        }

        /**
         * Sets the value of the personNamePrev property.
         * 
         * @param value
         *     allowed object is
         *     {@link PersonNamePrev }
         *     
         */
        public void setPersonNamePrev(PersonNamePrev value) {
            this.personNamePrev = value;
        }

        /**
         * Gets the value of the birthday property.
         * 
         * @return
         *     possible object is
         *     {@link Date }
         *     
         */
        public Date getBirthday() {
            return birthday;
        }

        /**
         * Sets the value of the birthday property.
         * 
         * @param value
         *     allowed object is
         *     {@link Date }
         *     
         */
        public void setBirthday(Date value) {
            this.birthday = value;
        }

        /**
         * Gets the value of the birthPlace property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBirthPlace() {
            return birthPlace;
        }

        /**
         * Sets the value of the birthPlace property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBirthPlace(String value) {
            this.birthPlace = value;
        }

        /**
         * Gets the value of the gender property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGender() {
            return gender;
        }

        /**
         * Sets the value of the gender property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGender(String value) {
            this.gender = value;
        }

        /**
         * Gets the value of the citizenship property.
         * 
         * @return
         *     possible object is
         *     {@link Citizenship }
         *     
         */
        public Citizenship getCitizenship() {
            return citizenship;
        }

        /**
         * Sets the value of the citizenship property.
         * 
         * @param value
         *     allowed object is
         *     {@link Citizenship }
         *     
         */
        public void setCitizenship(Citizenship value) {
            this.citizenship = value;
        }

        /**
         * Gets the value of the resident property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isResident() {
            return resident;
        }

        /**
         * Sets the value of the resident property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setResident(Boolean value) {
            this.resident = value;
        }

        /**
         * Gets the value of the dependents property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDependents() {
            return dependents;
        }

        /**
         * Sets the value of the dependents property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDependents(String value) {
            this.dependents = value;
        }

        /**
         * Gets the value of the maritalStatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMaritalStatus() {
            return maritalStatus;
        }

        /**
         * Sets the value of the maritalStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMaritalStatus(String value) {
            this.maritalStatus = value;
        }

        /**
         * Gets the value of the militaryStatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMilitaryStatus() {
            return militaryStatus;
        }

        /**
         * Sets the value of the militaryStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMilitaryStatus(String value) {
            this.militaryStatus = value;
        }

        /**
         * Gets the value of the totalExperiance property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getTotalExperiance() {
            return totalExperiance;
        }

        /**
         * Sets the value of the totalExperiance property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setTotalExperiance(Integer value) {
            this.totalExperiance = value;
        }

        /**
         * Gets the value of the weddingInfo property.
         * 
         * @return
         *     possible object is
         *     {@link AfsCustInfoType.PersonInfo.WeddingInfo }
         *     
         */
        public AfsCustInfoType.PersonInfo.WeddingInfo getWeddingInfo() {
            return weddingInfo;
        }

        /**
         * Sets the value of the weddingInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link AfsCustInfoType.PersonInfo.WeddingInfo }
         *     
         */
        public void setWeddingInfo(AfsCustInfoType.PersonInfo.WeddingInfo value) {
            this.weddingInfo = value;
        }

        /**
         * Gets the value of the militaryDelay property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMilitaryDelay() {
            return militaryDelay;
        }

        /**
         * Sets the value of the militaryDelay property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMilitaryDelay(String value) {
            this.militaryDelay = value;
        }

        /**
         * Gets the value of the addCitizenship property.
         * 
         * @return
         *     possible object is
         *     {@link AfsCustInfoType.PersonInfo.AddCitizenship }
         *     
         */
        public AfsCustInfoType.PersonInfo.AddCitizenship getAddCitizenship() {
            return addCitizenship;
        }

        /**
         * Sets the value of the addCitizenship property.
         * 
         * @param value
         *     allowed object is
         *     {@link AfsCustInfoType.PersonInfo.AddCitizenship }
         *     
         */
        public void setAddCitizenship(AfsCustInfoType.PersonInfo.AddCitizenship value) {
            this.addCitizenship = value;
        }

        /**
         * Gets the value of the educationStatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEducationStatus() {
            return educationStatus;
        }

        /**
         * Sets the value of the educationStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEducationStatus(String value) {
            this.educationStatus = value;
        }

        /**
         * Gets the value of the consularRegistry property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConsularRegistry() {
            return consularRegistry;
        }

        /**
         * Sets the value of the consularRegistry property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConsularRegistry(String value) {
            this.consularRegistry = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element ref="{}Country"/>
         *         &lt;element ref="{}CountryName" minOccurs="0"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class AddCitizenship {

            @XmlElement(name = "Country", required = true)
            protected String country;
            @XmlElement(name = "CountryName")
            protected String countryName;

            /**
             * Gets the value of the country property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCountry() {
                return country;
            }

            /**
             * Sets the value of the country property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCountry(String value) {
                this.country = value;
            }

            /**
             * Gets the value of the countryName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCountryName() {
                return countryName;
            }

            /**
             * Sets the value of the countryName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCountryName(String value) {
                this.countryName = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="RegDt" type="{}Date" minOccurs="0"/>
         *         &lt;element name="MarriageContract" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *         &lt;element name="DivisionProperty" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Childs" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "regDt",
            "marriageContract",
            "divisionProperty",
            "childs"
        })
        public static class WeddingInfo {

            @XmlElement(name = "RegDt")
            protected Date regDt;
            @XmlElement(name = "MarriageContract")
            protected Boolean marriageContract;
            @XmlElement(name = "DivisionProperty")
            protected String divisionProperty;
            @XmlElement(name = "Childs")
            protected Boolean childs;

            /**
             * Gets the value of the regDt property.
             * 
             * @return
             *     possible object is
             *     {@link Date }
             *     
             */
            public Date getRegDt() {
                return regDt;
            }

            /**
             * Sets the value of the regDt property.
             * 
             * @param value
             *     allowed object is
             *     {@link Date }
             *     
             */
            public void setRegDt(Date value) {
                this.regDt = value;
            }

            /**
             * Gets the value of the marriageContract property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isMarriageContract() {
                return marriageContract;
            }

            /**
             * Sets the value of the marriageContract property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setMarriageContract(Boolean value) {
                this.marriageContract = value;
            }

            /**
             * Gets the value of the divisionProperty property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDivisionProperty() {
                return divisionProperty;
            }

            /**
             * Sets the value of the divisionProperty property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDivisionProperty(String value) {
                this.divisionProperty = value;
            }

            /**
             * Gets the value of the childs property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isChilds() {
                return childs;
            }

            /**
             * Sets the value of the childs property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setChilds(Boolean value) {
                this.childs = value;
            }

        }

    }

}
