//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.19 at 11:25:25 AM MSK 
//


package com.farzoom.lime.adapter.cbs.service.integration.model.afs.response;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}ServerInfo"/>
 *         &lt;element name="BankSvcRs">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="SPInfo">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="Action" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ActionSNA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="RuleSetId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="RuleSetIdSNA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                             &lt;element ref="{}RequestId"/>
 *                             &lt;element ref="{}RequestVersion"/>
 *                             &lt;element name="RequestCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                             &lt;element name="RuleCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                             &lt;element name="MatchCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="MatchList" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="MatchRec" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;all>
 *                                       &lt;element ref="{}RequestId"/>
 *                                       &lt;element ref="{}RequestVersion"/>
 *                                       &lt;element name="RuleCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element ref="{}Desc" minOccurs="0"/>
 *                                       &lt;element name="New" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                                     &lt;/all>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element ref="{}Status"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "FDX")
public class SPRCustCheckResponse {

    @XmlElement(name = "ServerInfo", required = true)
    protected ServerInfoType serverInfo;
    @XmlElement(name = "BankSvcRs", required = true)
    protected SPRCustCheckResponse.BankSvcRs bankSvcRs;

    /**
     * Gets the value of the serverInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ServerInfoType }
     *     
     */
    public ServerInfoType getServerInfo() {
        return serverInfo;
    }

    /**
     * Sets the value of the serverInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServerInfoType }
     *     
     */
    public void setServerInfo(ServerInfoType value) {
        this.serverInfo = value;
    }

    /**
     * Gets the value of the bankSvcRs property.
     * 
     * @return
     *     possible object is
     *     {@link SPRCustCheckResponse.BankSvcRs }
     *     
     */
    public SPRCustCheckResponse.BankSvcRs getBankSvcRs() {
        return bankSvcRs;
    }

    /**
     * Sets the value of the bankSvcRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link SPRCustCheckResponse.BankSvcRs }
     *     
     */
    public void setBankSvcRs(SPRCustCheckResponse.BankSvcRs value) {
        this.bankSvcRs = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="SPInfo">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="Action" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ActionSNA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="RuleSetId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="RuleSetIdSNA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                   &lt;element ref="{}RequestId"/>
     *                   &lt;element ref="{}RequestVersion"/>
     *                   &lt;element name="RequestCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                   &lt;element name="RuleCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                   &lt;element name="MatchCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="MatchList" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="MatchRec" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;all>
     *                             &lt;element ref="{}RequestId"/>
     *                             &lt;element ref="{}RequestVersion"/>
     *                             &lt;element name="RuleCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element ref="{}Desc" minOccurs="0"/>
     *                             &lt;element name="New" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                           &lt;/all>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element ref="{}Status"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class BankSvcRs {

        @XmlElement(name = "SPInfo", required = true)
        protected SPRCustCheckResponse.BankSvcRs.SPInfo spInfo;
        @XmlElement(name = "MatchList")
        protected SPRCustCheckResponse.BankSvcRs.MatchList matchList;
        @XmlElement(name = "Status", required = true)
        protected Status status;

        /**
         * Gets the value of the spInfo property.
         * 
         * @return
         *     possible object is
         *     {@link SPRCustCheckResponse.BankSvcRs.SPInfo }
         *     
         */
        public SPRCustCheckResponse.BankSvcRs.SPInfo getSPInfo() {
            return spInfo;
        }

        /**
         * Sets the value of the spInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link SPRCustCheckResponse.BankSvcRs.SPInfo }
         *     
         */
        public void setSPInfo(SPRCustCheckResponse.BankSvcRs.SPInfo value) {
            this.spInfo = value;
        }

        /**
         * Gets the value of the matchList property.
         * 
         * @return
         *     possible object is
         *     {@link SPRCustCheckResponse.BankSvcRs.MatchList }
         *     
         */
        public SPRCustCheckResponse.BankSvcRs.MatchList getMatchList() {
            return matchList;
        }

        /**
         * Sets the value of the matchList property.
         * 
         * @param value
         *     allowed object is
         *     {@link SPRCustCheckResponse.BankSvcRs.MatchList }
         *     
         */
        public void setMatchList(SPRCustCheckResponse.BankSvcRs.MatchList value) {
            this.matchList = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link Status }
         *     
         */
        public Status getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link Status }
         *     
         */
        public void setStatus(Status value) {
            this.status = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="MatchRec" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;all>
         *                   &lt;element ref="{}RequestId"/>
         *                   &lt;element ref="{}RequestVersion"/>
         *                   &lt;element name="RuleCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element ref="{}Desc" minOccurs="0"/>
         *                   &lt;element name="New" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
         *                 &lt;/all>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "matchRec"
        })
        public static class MatchList {

            @XmlElement(name = "MatchRec", required = true)
            protected List<SPRCustCheckResponse.BankSvcRs.MatchList.MatchRec> matchRec;

            /**
             * Gets the value of the matchRec property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the matchRec property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getMatchRec().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link SPRCustCheckResponse.BankSvcRs.MatchList.MatchRec }
             * 
             * 
             */
            public List<SPRCustCheckResponse.BankSvcRs.MatchList.MatchRec> getMatchRec() {
                if (matchRec == null) {
                    matchRec = new ArrayList<SPRCustCheckResponse.BankSvcRs.MatchList.MatchRec>();
                }
                return this.matchRec;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;all>
             *         &lt;element ref="{}RequestId"/>
             *         &lt;element ref="{}RequestVersion"/>
             *         &lt;element name="RuleCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element ref="{}Desc" minOccurs="0"/>
             *         &lt;element name="New" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
             *       &lt;/all>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {

            })
            public static class MatchRec {

                @XmlElement(name = "RequestId", required = true)
                protected String requestId;
                @XmlElement(name = "RequestVersion")
                protected int requestVersion;
                @XmlElement(name = "RuleCode", required = true)
                protected String ruleCode;
                @XmlElement(name = "Desc")
                protected String desc;
                @XmlElement(name = "New")
                protected Integer _new;

                /**
                 * Gets the value of the requestId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRequestId() {
                    return requestId;
                }

                /**
                 * Sets the value of the requestId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRequestId(String value) {
                    this.requestId = value;
                }

                /**
                 * Gets the value of the requestVersion property.
                 * 
                 */
                public int getRequestVersion() {
                    return requestVersion;
                }

                /**
                 * Sets the value of the requestVersion property.
                 * 
                 */
                public void setRequestVersion(int value) {
                    this.requestVersion = value;
                }

                /**
                 * Gets the value of the ruleCode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRuleCode() {
                    return ruleCode;
                }

                /**
                 * Sets the value of the ruleCode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRuleCode(String value) {
                    this.ruleCode = value;
                }

                /**
                 * Gets the value of the desc property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDesc() {
                    return desc;
                }

                /**
                 * Sets the value of the desc property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDesc(String value) {
                    this.desc = value;
                }

                /**
                 * Gets the value of the new property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getNew() {
                    return _new;
                }

                /**
                 * Sets the value of the new property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setNew(Integer value) {
                    this._new = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="Action" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ActionSNA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="RuleSetId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="RuleSetIdSNA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *         &lt;element ref="{}RequestId"/>
         *         &lt;element ref="{}RequestVersion"/>
         *         &lt;element name="RequestCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
         *         &lt;element name="RuleCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
         *         &lt;element name="MatchCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class SPInfo {

            @XmlElement(name = "Action", required = true)
            protected String action;
            @XmlElement(name = "ActionSNA")
            protected String actionSNA;
            @XmlElement(name = "RuleSetId")
            protected String ruleSetId;
            @XmlElement(name = "RuleSetIdSNA")
            protected String ruleSetIdSNA;
            @XmlElement(name = "Duration")
            protected long duration;
            @XmlElement(name = "RequestId", required = true)
            protected String requestId;
            @XmlElement(name = "RequestVersion")
            protected int requestVersion;
            @XmlElement(name = "RequestCount")
            protected Integer requestCount;
            @XmlElement(name = "RuleCount")
            protected Integer ruleCount;
            @XmlElement(name = "MatchCount")
            protected Integer matchCount;

            /**
             * Gets the value of the action property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAction() {
                return action;
            }

            /**
             * Sets the value of the action property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAction(String value) {
                this.action = value;
            }

            /**
             * Gets the value of the actionSNA property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getActionSNA() {
                return actionSNA;
            }

            /**
             * Sets the value of the actionSNA property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setActionSNA(String value) {
                this.actionSNA = value;
            }

            /**
             * Gets the value of the ruleSetId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRuleSetId() {
                return ruleSetId;
            }

            /**
             * Sets the value of the ruleSetId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRuleSetId(String value) {
                this.ruleSetId = value;
            }

            /**
             * Gets the value of the ruleSetIdSNA property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRuleSetIdSNA() {
                return ruleSetIdSNA;
            }

            /**
             * Sets the value of the ruleSetIdSNA property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRuleSetIdSNA(String value) {
                this.ruleSetIdSNA = value;
            }

            /**
             * Gets the value of the duration property.
             * 
             */
            public long getDuration() {
                return duration;
            }

            /**
             * Sets the value of the duration property.
             * 
             */
            public void setDuration(long value) {
                this.duration = value;
            }

            /**
             * Gets the value of the requestId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRequestId() {
                return requestId;
            }

            /**
             * Sets the value of the requestId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRequestId(String value) {
                this.requestId = value;
            }

            /**
             * Gets the value of the requestVersion property.
             * 
             */
            public int getRequestVersion() {
                return requestVersion;
            }

            /**
             * Sets the value of the requestVersion property.
             * 
             */
            public void setRequestVersion(int value) {
                this.requestVersion = value;
            }

            /**
             * Gets the value of the requestCount property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getRequestCount() {
                return requestCount;
            }

            /**
             * Sets the value of the requestCount property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setRequestCount(Integer value) {
                this.requestCount = value;
            }

            /**
             * Gets the value of the ruleCount property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getRuleCount() {
                return ruleCount;
            }

            /**
             * Sets the value of the ruleCount property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setRuleCount(Integer value) {
                this.ruleCount = value;
            }

            /**
             * Gets the value of the matchCount property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getMatchCount() {
                return matchCount;
            }

            /**
             * Sets the value of the matchCount property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setMatchCount(Integer value) {
                this.matchCount = value;
            }

        }

    }

}
