//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.11 at 07:50:00 AM MSK 
//


package com.farzoom.lime.adapter.cbs.service.integration.model.cre.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;


/**
 * <p>Java class for cofinContributionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cofinContributionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="YEAR" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="PERSONAL_SUM" type="{}moneyValueType" minOccurs="0"/>
 *         &lt;element name="EMPLOYER_SUM" type="{}moneyValueType" minOccurs="0"/>
 *         &lt;element name="COFINANCE_SUM" type="{}moneyValueType" minOccurs="0"/>
 *         &lt;element name="COFINANCE_TYPE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PENSION_RQ_SIGN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cofinContributionType", propOrder = {
    "year",
    "personalsum",
    "employersum",
    "cofinancesum",
    "cofinancetype",
    "pensionrqsign"
})
public class CofinContributionType {

    @XmlElement(name = "YEAR")
    protected Integer year;
    @XmlElement(name = "PERSONAL_SUM")
    protected BigDecimal personalsum;
    @XmlElement(name = "EMPLOYER_SUM")
    protected BigDecimal employersum;
    @XmlElement(name = "COFINANCE_SUM")
    protected BigDecimal cofinancesum;
    @XmlElement(name = "COFINANCE_TYPE")
    protected String cofinancetype;
    @XmlElement(name = "PENSION_RQ_SIGN")
    protected String pensionrqsign;

    /**
     * Gets the value of the year property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getYEAR() {
        return year;
    }

    /**
     * Sets the value of the year property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setYEAR(Integer value) {
        this.year = value;
    }

    /**
     * Gets the value of the personalsum property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPERSONALSUM() {
        return personalsum;
    }

    /**
     * Sets the value of the personalsum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPERSONALSUM(BigDecimal value) {
        this.personalsum = value;
    }

    /**
     * Gets the value of the employersum property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEMPLOYERSUM() {
        return employersum;
    }

    /**
     * Sets the value of the employersum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEMPLOYERSUM(BigDecimal value) {
        this.employersum = value;
    }

    /**
     * Gets the value of the cofinancesum property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCOFINANCESUM() {
        return cofinancesum;
    }

    /**
     * Sets the value of the cofinancesum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCOFINANCESUM(BigDecimal value) {
        this.cofinancesum = value;
    }

    /**
     * Gets the value of the cofinancetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOFINANCETYPE() {
        return cofinancetype;
    }

    /**
     * Sets the value of the cofinancetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOFINANCETYPE(String value) {
        this.cofinancetype = value;
    }

    /**
     * Gets the value of the pensionrqsign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPENSIONRQSIGN() {
        return pensionrqsign;
    }

    /**
     * Sets the value of the pensionrqsign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPENSIONRQSIGN(String value) {
        this.pensionrqsign = value;
    }

}
