//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.11 at 07:50:00 AM MSK 
//


package com.farzoom.lime.adapter.cbs.service.integration.model.cre.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for generalType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="generalType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NAMES" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="DOCUMENTS" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ADDRESSES" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="PHONES" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="EMPLOYMENTS" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="PASSPORT_CHECKS" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="COMPANY_CHECKS" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="EXTENSION" type="{}extensionType" minOccurs="0"/>
 *         &lt;element name="INQUIRIES" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "generalType", propOrder = {
    "names",
    "documents",
    "addresses",
    "phones",
    "employments",
    "passportchecks",
    "companychecks",
    "extension",
    "inquiries"
})
public class GeneralType {

    @XmlElement(name = "NAMES")
    protected int names;
    @XmlElement(name = "DOCUMENTS")
    protected int documents;
    @XmlElement(name = "ADDRESSES")
    protected int addresses;
    @XmlElement(name = "PHONES")
    protected int phones;
    @XmlElement(name = "EMPLOYMENTS")
    protected int employments;
    @XmlElement(name = "PASSPORT_CHECKS")
    protected int passportchecks;
    @XmlElement(name = "COMPANY_CHECKS")
    protected int companychecks;
    @XmlElement(name = "EXTENSION")
    protected ExtensionType extension;
    @XmlElement(name = "INQUIRIES")
    protected Integer inquiries;

    /**
     * Gets the value of the names property.
     * 
     */
    public int getNAMES() {
        return names;
    }

    /**
     * Sets the value of the names property.
     * 
     */
    public void setNAMES(int value) {
        this.names = value;
    }

    /**
     * Gets the value of the documents property.
     * 
     */
    public int getDOCUMENTS() {
        return documents;
    }

    /**
     * Sets the value of the documents property.
     * 
     */
    public void setDOCUMENTS(int value) {
        this.documents = value;
    }

    /**
     * Gets the value of the addresses property.
     * 
     */
    public int getADDRESSES() {
        return addresses;
    }

    /**
     * Sets the value of the addresses property.
     * 
     */
    public void setADDRESSES(int value) {
        this.addresses = value;
    }

    /**
     * Gets the value of the phones property.
     * 
     */
    public int getPHONES() {
        return phones;
    }

    /**
     * Sets the value of the phones property.
     * 
     */
    public void setPHONES(int value) {
        this.phones = value;
    }

    /**
     * Gets the value of the employments property.
     * 
     */
    public int getEMPLOYMENTS() {
        return employments;
    }

    /**
     * Sets the value of the employments property.
     * 
     */
    public void setEMPLOYMENTS(int value) {
        this.employments = value;
    }

    /**
     * Gets the value of the passportchecks property.
     * 
     */
    public int getPASSPORTCHECKS() {
        return passportchecks;
    }

    /**
     * Sets the value of the passportchecks property.
     * 
     */
    public void setPASSPORTCHECKS(int value) {
        this.passportchecks = value;
    }

    /**
     * Gets the value of the companychecks property.
     * 
     */
    public int getCOMPANYCHECKS() {
        return companychecks;
    }

    /**
     * Sets the value of the companychecks property.
     * 
     */
    public void setCOMPANYCHECKS(int value) {
        this.companychecks = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionType }
     *     
     */
    public ExtensionType getEXTENSION() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionType }
     *     
     */
    public void setEXTENSION(ExtensionType value) {
        this.extension = value;
    }

    /**
     * Gets the value of the inquiries property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getINQUIRIES() {
        return inquiries;
    }

    /**
     * Sets the value of the inquiries property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setINQUIRIES(Integer value) {
        this.inquiries = value;
    }

}
