//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.11 at 07:50:00 AM MSK 
//


package com.farzoom.lime.adapter.cbs.service.integration.model.cre.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;


/**
 * <p>Java class for infopartType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="infopartType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TYPE" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="APPLICATION_NUMBER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="APPLICATION_DATE" type="{}dateType" minOccurs="0"/>
 *         &lt;element name="STATUS" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="STATUS_DATE" type="{}dateType" minOccurs="0"/>
 *         &lt;element name="REQ_CRED_CATEGORY" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="CREDITOR_TYPE" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="APPLICATION_WAY" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="APPROVAL_EXPIRATION_DATE" type="{}dateType" minOccurs="0"/>
 *         &lt;element name="ACCOUNT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CRED_CATEGORY" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="TWO_CONS_PAY_MISSED" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="FULLY_PAID_OFF" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="APP_AMOUNT" type="{}moneyValueType" minOccurs="0"/>
 *         &lt;element name="APP_CURRENCY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="REJECT_REASON" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="REJECT_COMMENTS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="INFO_SOURCES" type="{}infoSourcesType"/>
 *         &lt;element name="EXTENSION" type="{}extensionType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "infopartType", propOrder = {
    "type",
    "applicationnumber",
    "applicationdate",
    "status",
    "statusdate",
    "reqcredcategory",
    "creditortype",
    "applicationway",
    "approvalexpirationdate",
    "account",
    "credcategory",
    "twoconspaymissed",
    "fullypaidoff",
    "appamount",
    "appcurrency",
    "rejectreason",
    "rejectcomments",
    "infosources",
    "extension"
})
public class InfopartType {

    @XmlElement(name = "TYPE")
    protected Integer type;
    @XmlElement(name = "APPLICATION_NUMBER")
    protected String applicationnumber;
    @XmlElement(name = "APPLICATION_DATE")
    protected String applicationdate;
    @XmlElement(name = "STATUS")
    protected Integer status;
    @XmlElement(name = "STATUS_DATE")
    protected String statusdate;
    @XmlElement(name = "REQ_CRED_CATEGORY")
    protected Integer reqcredcategory;
    @XmlElement(name = "CREDITOR_TYPE")
    protected Integer creditortype;
    @XmlElement(name = "APPLICATION_WAY")
    protected Integer applicationway;
    @XmlElement(name = "APPROVAL_EXPIRATION_DATE")
    protected String approvalexpirationdate;
    @XmlElement(name = "ACCOUNT")
    protected String account;
    @XmlElement(name = "CRED_CATEGORY")
    protected Integer credcategory;
    @XmlElement(name = "TWO_CONS_PAY_MISSED")
    protected Integer twoconspaymissed;
    @XmlElement(name = "FULLY_PAID_OFF")
    protected Integer fullypaidoff;
    @XmlElement(name = "APP_AMOUNT")
    protected BigDecimal appamount;
    @XmlElement(name = "APP_CURRENCY")
    protected String appcurrency;
    @XmlElement(name = "REJECT_REASON")
    protected Integer rejectreason;
    @XmlElement(name = "REJECT_COMMENTS")
    protected String rejectcomments;
    @XmlElement(name = "INFO_SOURCES", required = true)
    protected InfoSourcesType infosources;
    @XmlElement(name = "EXTENSION")
    protected ExtensionType extension;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTYPE() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTYPE(Integer value) {
        this.type = value;
    }

    /**
     * Gets the value of the applicationnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPPLICATIONNUMBER() {
        return applicationnumber;
    }

    /**
     * Sets the value of the applicationnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPPLICATIONNUMBER(String value) {
        this.applicationnumber = value;
    }

    /**
     * Gets the value of the applicationdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPPLICATIONDATE() {
        return applicationdate;
    }

    /**
     * Sets the value of the applicationdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPPLICATIONDATE(String value) {
        this.applicationdate = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSTATUS() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSTATUS(Integer value) {
        this.status = value;
    }

    /**
     * Gets the value of the statusdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATUSDATE() {
        return statusdate;
    }

    /**
     * Sets the value of the statusdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATUSDATE(String value) {
        this.statusdate = value;
    }

    /**
     * Gets the value of the reqcredcategory property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getREQCREDCATEGORY() {
        return reqcredcategory;
    }

    /**
     * Sets the value of the reqcredcategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setREQCREDCATEGORY(Integer value) {
        this.reqcredcategory = value;
    }

    /**
     * Gets the value of the creditortype property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCREDITORTYPE() {
        return creditortype;
    }

    /**
     * Sets the value of the creditortype property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCREDITORTYPE(Integer value) {
        this.creditortype = value;
    }

    /**
     * Gets the value of the applicationway property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAPPLICATIONWAY() {
        return applicationway;
    }

    /**
     * Sets the value of the applicationway property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAPPLICATIONWAY(Integer value) {
        this.applicationway = value;
    }

    /**
     * Gets the value of the approvalexpirationdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPPROVALEXPIRATIONDATE() {
        return approvalexpirationdate;
    }

    /**
     * Sets the value of the approvalexpirationdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPPROVALEXPIRATIONDATE(String value) {
        this.approvalexpirationdate = value;
    }

    /**
     * Gets the value of the account property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACCOUNT() {
        return account;
    }

    /**
     * Sets the value of the account property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCOUNT(String value) {
        this.account = value;
    }

    /**
     * Gets the value of the credcategory property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCREDCATEGORY() {
        return credcategory;
    }

    /**
     * Sets the value of the credcategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCREDCATEGORY(Integer value) {
        this.credcategory = value;
    }

    /**
     * Gets the value of the twoconspaymissed property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTWOCONSPAYMISSED() {
        return twoconspaymissed;
    }

    /**
     * Sets the value of the twoconspaymissed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTWOCONSPAYMISSED(Integer value) {
        this.twoconspaymissed = value;
    }

    /**
     * Gets the value of the fullypaidoff property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFULLYPAIDOFF() {
        return fullypaidoff;
    }

    /**
     * Sets the value of the fullypaidoff property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFULLYPAIDOFF(Integer value) {
        this.fullypaidoff = value;
    }

    /**
     * Gets the value of the appamount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAPPAMOUNT() {
        return appamount;
    }

    /**
     * Sets the value of the appamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAPPAMOUNT(BigDecimal value) {
        this.appamount = value;
    }

    /**
     * Gets the value of the appcurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPPCURRENCY() {
        return appcurrency;
    }

    /**
     * Sets the value of the appcurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPPCURRENCY(String value) {
        this.appcurrency = value;
    }

    /**
     * Gets the value of the rejectreason property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getREJECTREASON() {
        return rejectreason;
    }

    /**
     * Sets the value of the rejectreason property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setREJECTREASON(Integer value) {
        this.rejectreason = value;
    }

    /**
     * Gets the value of the rejectcomments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREJECTCOMMENTS() {
        return rejectcomments;
    }

    /**
     * Sets the value of the rejectcomments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREJECTCOMMENTS(String value) {
        this.rejectcomments = value;
    }

    /**
     * Gets the value of the infosources property.
     * 
     * @return
     *     possible object is
     *     {@link InfoSourcesType }
     *     
     */
    public InfoSourcesType getINFOSOURCES() {
        return infosources;
    }

    /**
     * Sets the value of the infosources property.
     * 
     * @param value
     *     allowed object is
     *     {@link InfoSourcesType }
     *     
     */
    public void setINFOSOURCES(InfoSourcesType value) {
        this.infosources = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionType }
     *     
     */
    public ExtensionType getEXTENSION() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionType }
     *     
     */
    public void setEXTENSION(ExtensionType value) {
        this.extension = value;
    }

}
