//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.11 at 07:50:00 AM MSK 
//


package com.farzoom.lime.adapter.cbs.service.integration.model.cre.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;


/**
 * <p>Java class for specialPartType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="specialPartType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FORM" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
 *         &lt;element name="YEAR" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="SAVINGS" type="{}moneyValueType" minOccurs="0"/>
 *         &lt;element name="MATERNITY_SAVINGS" type="{}moneyValueType" minOccurs="0"/>
 *         &lt;element name="FROM_NPF_TO_PFR" type="{}moneyValueType" minOccurs="0"/>
 *         &lt;element name="MATERNITY_TOTAL" type="{}moneyValueType" minOccurs="0"/>
 *         &lt;element name="AMC_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PORTFOLIO_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NPF_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="STOP_YEAR" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="STOP_AMC_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="STOP_PORTFOLIO_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="STOP_NPF_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "specialPartType", propOrder = {
    "form",
    "year",
    "savings",
    "maternitysavings",
    "fromnpftopfr",
    "maternitytotal",
    "amcname",
    "portfolioname",
    "npfname",
    "stopyear",
    "stopamcname",
    "stopportfolioname",
    "stopnpfname"
})
public class SpecialPartType {

    @XmlElement(name = "FORM")
    protected Byte form;
    @XmlElement(name = "YEAR")
    protected Integer year;
    @XmlElement(name = "SAVINGS")
    protected BigDecimal savings;
    @XmlElement(name = "MATERNITY_SAVINGS")
    protected BigDecimal maternitysavings;
    @XmlElement(name = "FROM_NPF_TO_PFR")
    protected BigDecimal fromnpftopfr;
    @XmlElement(name = "MATERNITY_TOTAL")
    protected BigDecimal maternitytotal;
    @XmlElement(name = "AMC_NAME")
    protected String amcname;
    @XmlElement(name = "PORTFOLIO_NAME")
    protected String portfolioname;
    @XmlElement(name = "NPF_NAME")
    protected String npfname;
    @XmlElement(name = "STOP_YEAR")
    protected Integer stopyear;
    @XmlElement(name = "STOP_AMC_NAME")
    protected String stopamcname;
    @XmlElement(name = "STOP_PORTFOLIO_NAME")
    protected String stopportfolioname;
    @XmlElement(name = "STOP_NPF_NAME")
    protected String stopnpfname;

    /**
     * Gets the value of the form property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getFORM() {
        return form;
    }

    /**
     * Sets the value of the form property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setFORM(Byte value) {
        this.form = value;
    }

    /**
     * Gets the value of the year property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getYEAR() {
        return year;
    }

    /**
     * Sets the value of the year property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setYEAR(Integer value) {
        this.year = value;
    }

    /**
     * Gets the value of the savings property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSAVINGS() {
        return savings;
    }

    /**
     * Sets the value of the savings property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSAVINGS(BigDecimal value) {
        this.savings = value;
    }

    /**
     * Gets the value of the maternitysavings property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMATERNITYSAVINGS() {
        return maternitysavings;
    }

    /**
     * Sets the value of the maternitysavings property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMATERNITYSAVINGS(BigDecimal value) {
        this.maternitysavings = value;
    }

    /**
     * Gets the value of the fromnpftopfr property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFROMNPFTOPFR() {
        return fromnpftopfr;
    }

    /**
     * Sets the value of the fromnpftopfr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFROMNPFTOPFR(BigDecimal value) {
        this.fromnpftopfr = value;
    }

    /**
     * Gets the value of the maternitytotal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMATERNITYTOTAL() {
        return maternitytotal;
    }

    /**
     * Sets the value of the maternitytotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMATERNITYTOTAL(BigDecimal value) {
        this.maternitytotal = value;
    }

    /**
     * Gets the value of the amcname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAMCNAME() {
        return amcname;
    }

    /**
     * Sets the value of the amcname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAMCNAME(String value) {
        this.amcname = value;
    }

    /**
     * Gets the value of the portfolioname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPORTFOLIONAME() {
        return portfolioname;
    }

    /**
     * Sets the value of the portfolioname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPORTFOLIONAME(String value) {
        this.portfolioname = value;
    }

    /**
     * Gets the value of the npfname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNPFNAME() {
        return npfname;
    }

    /**
     * Sets the value of the npfname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNPFNAME(String value) {
        this.npfname = value;
    }

    /**
     * Gets the value of the stopyear property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSTOPYEAR() {
        return stopyear;
    }

    /**
     * Sets the value of the stopyear property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSTOPYEAR(Integer value) {
        this.stopyear = value;
    }

    /**
     * Gets the value of the stopamcname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTOPAMCNAME() {
        return stopamcname;
    }

    /**
     * Sets the value of the stopamcname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTOPAMCNAME(String value) {
        this.stopamcname = value;
    }

    /**
     * Gets the value of the stopportfolioname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTOPPORTFOLIONAME() {
        return stopportfolioname;
    }

    /**
     * Sets the value of the stopportfolioname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTOPPORTFOLIONAME(String value) {
        this.stopportfolioname = value;
    }

    /**
     * Gets the value of the stopnpfname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTOPNPFNAME() {
        return stopnpfname;
    }

    /**
     * Sets the value of the stopnpfname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTOPNPFNAME(String value) {
        this.stopnpfname = value;
    }

}
