//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.26 at 09:27:04 AM MSK 
//


package com.farzoom.lime.adapter.cbs.service.integration.model.fileadd.request;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ServerInfo" type="{}ServerInfo_Type"/>
 *         &lt;element name="BankSvcRq">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="FileList">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="FileRec" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element ref="{}Name"/>
 *                                       &lt;element name="FileId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="Data">
 *                                         &lt;complexType>
 *                                           &lt;simpleContent>
 *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>base64Binary">
 *                                               &lt;attribute name="Extension" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="AttachmentIsTextData" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                                               &lt;attribute name="ContentId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="EndOfData" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                                               &lt;attribute name="TimedOut" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                                             &lt;/extension>
 *                                           &lt;/simpleContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="BCId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "serverInfo",
    "bankSvcRq"
})
@XmlRootElement(name = "FDX")
public class FileAddRequest {

    @XmlElement(name = "ServerInfo", required = true)
    protected ServerInfoType serverInfo;
    @XmlElement(name = "BankSvcRq", required = true)
    protected FileAddRequest.BankSvcRq bankSvcRq;

    /**
     * Gets the value of the serverInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ServerInfoType }
     *     
     */
    public ServerInfoType getServerInfo() {
        return serverInfo;
    }

    /**
     * Sets the value of the serverInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServerInfoType }
     *     
     */
    public void setServerInfo(ServerInfoType value) {
        this.serverInfo = value;
    }

    /**
     * Gets the value of the bankSvcRq property.
     * 
     * @return
     *     possible object is
     *     {@link FileAddRequest.BankSvcRq }
     *     
     */
    public FileAddRequest.BankSvcRq getBankSvcRq() {
        return bankSvcRq;
    }

    /**
     * Sets the value of the bankSvcRq property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileAddRequest.BankSvcRq }
     *     
     */
    public void setBankSvcRq(FileAddRequest.BankSvcRq value) {
        this.bankSvcRq = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="FileList">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="FileRec" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element ref="{}Name"/>
     *                             &lt;element name="FileId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="Data">
     *                               &lt;complexType>
     *                                 &lt;simpleContent>
     *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>base64Binary">
     *                                     &lt;attribute name="Extension" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="AttachmentIsTextData" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                                     &lt;attribute name="ContentId" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="EndOfData" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                                     &lt;attribute name="TimedOut" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                                   &lt;/extension>
     *                                 &lt;/simpleContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="BCId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fileList",
        "bcId"
    })
    public static class BankSvcRq {

        @XmlElement(name = "FileList", required = true)
        protected FileAddRequest.BankSvcRq.FileList fileList;
        @XmlElement(name = "BCId")
        protected String bcId;

        /**
         * Gets the value of the fileList property.
         * 
         * @return
         *     possible object is
         *     {@link FileAddRequest.BankSvcRq.FileList }
         *     
         */
        public FileAddRequest.BankSvcRq.FileList getFileList() {
            return fileList;
        }

        /**
         * Sets the value of the fileList property.
         * 
         * @param value
         *     allowed object is
         *     {@link FileAddRequest.BankSvcRq.FileList }
         *     
         */
        public void setFileList(FileAddRequest.BankSvcRq.FileList value) {
            this.fileList = value;
        }

        /**
         * Gets the value of the bcId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBCId() {
            return bcId;
        }

        /**
         * Sets the value of the bcId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBCId(String value) {
            this.bcId = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="FileRec" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element ref="{}Name"/>
         *                   &lt;element name="FileId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="Data">
         *                     &lt;complexType>
         *                       &lt;simpleContent>
         *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>base64Binary">
         *                           &lt;attribute name="Extension" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="AttachmentIsTextData" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *                           &lt;attribute name="ContentId" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="EndOfData" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *                           &lt;attribute name="TimedOut" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *                         &lt;/extension>
         *                       &lt;/simpleContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "fileRec"
        })
        public static class FileList {

            @XmlElement(name = "FileRec", required = true)
            protected List<FileAddRequest.BankSvcRq.FileList.FileRec> fileRec;

            /**
             * Gets the value of the fileRec property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the fileRec property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getFileRec().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link FileAddRequest.BankSvcRq.FileList.FileRec }
             * 
             * 
             */
            public List<FileAddRequest.BankSvcRq.FileList.FileRec> getFileRec() {
                if (fileRec == null) {
                    fileRec = new ArrayList<FileAddRequest.BankSvcRq.FileList.FileRec>();
                }
                return this.fileRec;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element ref="{}Name"/>
             *         &lt;element name="FileId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="Data">
             *           &lt;complexType>
             *             &lt;simpleContent>
             *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>base64Binary">
             *                 &lt;attribute name="Extension" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="AttachmentIsTextData" type="{http://www.w3.org/2001/XMLSchema}boolean" />
             *                 &lt;attribute name="ContentId" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="EndOfData" type="{http://www.w3.org/2001/XMLSchema}boolean" />
             *                 &lt;attribute name="TimedOut" type="{http://www.w3.org/2001/XMLSchema}boolean" />
             *               &lt;/extension>
             *             &lt;/simpleContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "name",
                "fileId",
                "data"
            })
            public static class FileRec {

                @XmlElement(name = "Name", required = true)
                protected String name;
                @XmlElement(name = "FileId")
                protected String fileId;
                @XmlElement(name = "Data", required = true)
                protected FileAddRequest.BankSvcRq.FileList.FileRec.Data data;

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the fileId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFileId() {
                    return fileId;
                }

                /**
                 * Sets the value of the fileId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFileId(String value) {
                    this.fileId = value;
                }

                /**
                 * Gets the value of the data property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link FileAddRequest.BankSvcRq.FileList.FileRec.Data }
                 *     
                 */
                public FileAddRequest.BankSvcRq.FileList.FileRec.Data getData() {
                    return data;
                }

                /**
                 * Sets the value of the data property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link FileAddRequest.BankSvcRq.FileList.FileRec.Data }
                 *     
                 */
                public void setData(FileAddRequest.BankSvcRq.FileList.FileRec.Data value) {
                    this.data = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;simpleContent>
                 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>base64Binary">
                 *       &lt;attribute name="Extension" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="AttachmentIsTextData" type="{http://www.w3.org/2001/XMLSchema}boolean" />
                 *       &lt;attribute name="ContentId" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="EndOfData" type="{http://www.w3.org/2001/XMLSchema}boolean" />
                 *       &lt;attribute name="TimedOut" type="{http://www.w3.org/2001/XMLSchema}boolean" />
                 *     &lt;/extension>
                 *   &lt;/simpleContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "value"
                })
                public static class Data {

                    @XmlValue
                    protected byte[] value;
                    @XmlAttribute(name = "Extension")
                    protected String extension;
                    @XmlAttribute(name = "AttachmentIsTextData")
                    protected Boolean attachmentIsTextData;
                    @XmlAttribute(name = "ContentId")
                    protected String contentId;
                    @XmlAttribute(name = "EndOfData")
                    protected Boolean endOfData;
                    @XmlAttribute(name = "TimedOut")
                    protected Boolean timedOut;

                    /**
                     * Gets the value of the value property.
                     * 
                     * @return
                     *     possible object is
                     *     byte[]
                     */
                    public byte[] getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     * 
                     * @param value
                     *     allowed object is
                     *     byte[]
                     */
                    public void setValue(byte[] value) {
                        this.value = value;
                    }

                    /**
                     * Gets the value of the extension property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getExtension() {
                        return extension;
                    }

                    /**
                     * Sets the value of the extension property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setExtension(String value) {
                        this.extension = value;
                    }

                    /**
                     * Gets the value of the attachmentIsTextData property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Boolean }
                     *     
                     */
                    public Boolean isAttachmentIsTextData() {
                        return attachmentIsTextData;
                    }

                    /**
                     * Sets the value of the attachmentIsTextData property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Boolean }
                     *     
                     */
                    public void setAttachmentIsTextData(Boolean value) {
                        this.attachmentIsTextData = value;
                    }

                    /**
                     * Gets the value of the contentId property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getContentId() {
                        return contentId;
                    }

                    /**
                     * Sets the value of the contentId property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setContentId(String value) {
                        this.contentId = value;
                    }

                    /**
                     * Gets the value of the endOfData property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Boolean }
                     *     
                     */
                    public Boolean isEndOfData() {
                        return endOfData;
                    }

                    /**
                     * Sets the value of the endOfData property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Boolean }
                     *     
                     */
                    public void setEndOfData(Boolean value) {
                        this.endOfData = value;
                    }

                    /**
                     * Gets the value of the timedOut property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Boolean }
                     *     
                     */
                    public Boolean isTimedOut() {
                        return timedOut;
                    }

                    /**
                     * Sets the value of the timedOut property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Boolean }
                     *     
                     */
                    public void setTimedOut(Boolean value) {
                        this.timedOut = value;
                    }

                }

            }

        }

    }

}
